site_name: My Guide
theme:
  name: material
nav:
  - Inicio: index.md
  - Teoria:
      - Modelado de Amenazas: teoria/amenazas-modelado.md
      - Ataque a Redes: teoria/ataque-redes.md
      - Infiltracion: teoria/infiltracion.md
      - Vulnerabilidades en Sitios Web: teoria/vulnerabilidades-web.md
  - Lenguajes:
      - Python:
          - Introduccion: lenguages/python/00_Introduccion.md
          - Fundamentos: lenguages/python/01_Fundamentos.md
          - Estructuras de Control: lenguages/python/02_Estructuras_de_control.md
          - Estructuras de Datos: lenguages/python/03_Estructuras_de_datos.md
          - Funciones: lenguages/python/04_Funciones.md
          - Manejo de Errores: lenguages/python/05_Manejo_de_errores.md
          - Entradas y Salidas: lenguages/python/06_Entrada_y_Salida.md
          - Modulos y Paquetes: lenguages/python/07_Modulos_y_Paquetes.md
  - Herramientas:
      - Comandos Comunes: herramientas/general-cheatsheet.md
      - NMAP: herramientas/nmap.md
      - Metasploit: herramientas/metasploit.md
      - Metasploitable VM: herramientas/metasploitableVM.md
      - Armitage: herramientas/armitage.md
      - WPScan: herramientas/wpscan.md
  - Pentesting:
      - Introduccion: pentest/introduccion.md
      - Pentest en APIs: pentest/pentest-apis.md
  - Laboratorio:
      - NMAP: laboratorio/nmap-lab.md
      - EtterCap: laboratorio/ettercap-lab.md
      - WireShark: laboratorio/wireshark-lab.md
      - Metasploit: laboratorio/metasploit-lab.md
      - Metasploitable VM: laboratorio/metasploitableVM.md
      - Nikto (UNDER CONSTRUCTION): laboratorio/nikto.md
      - Burpsuite: laboratorio/burpsuite-lab.md
      - Transferencia de Archivos: laboratorio/transferencia-archivos.md
      - Ataque a Redes Inalambricas: laboratorio/ataques-redes-inalambricas-lab.md
      - Como Vulnerar un Sitio Web: laboratorio/vulnerar-sitioweb.md
      - WPScan: laboratorio/wpscan-lab.md
  - Configuracion de Maquina:
      - Particiones: configuracion-maquina/particiones.md
      - Terminal: configuracion-maquina/terminal.md
      - GUI: configuracion-maquina/gui.md
      - Extras: configuracion-maquina/extras.md
      - Herramientas: configuracion-maquina/herramientas.md

site_url: https://emm4nuelcm.github.io/my-knowledge-base/
extra_css:
  - assets/extra.css
