site_name: Mi Guia Personal
theme:
  name: material
nav:
  - Inicio: index.md
  - Teoria:
      - Modelado de Amenazas: teoria/amenazas-modelado.md
      - Ataque a Redes: teoria/ataque-redes.md
      - Infiltracion: teoria/infiltracion.md
      - Vulnerabilidades en Sitios Web: teoria/vulnerabilidades-web.md
  - Cloud:
      - AWS:
          - Introducción: cloud/aws/1-introduction.md
          - Fundamentos de Seguridad (2a Edición):
              - Introducción: cloud/aws/aws-security-fundamentals-second-edition/1-introduction.md
              - Seguridad de la Nube: cloud/aws/aws-security-fundamentals-second-edition/2-security-of-the-cloud.md
              - Seguridad en la Nube: cloud/aws/aws-security-fundamentals-second-edition/3-security-in-the-cloud.md
          - Cloud Practitioner Essentials:
              - 1. Introducción a la Nube:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/1-introduction-to-the-cloud/1-introduction.md
                  - AWS Cloud: cloud/aws/aws-cloud-practitioner-essentials/1-introduction-to-the-cloud/2-the-aws-cloud.md
                  - Cloud en la Vida Real: cloud/aws/aws-cloud-practitioner-essentials/1-introduction-to-the-cloud/3-cloud-in-real-life.md
              - 2. Cómputo en la Nube:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/2-compute-in-the-cloud/1-introduction.md
                  - Cómputo en la Nube: cloud/aws/aws-cloud-practitioner-essentials/2-compute-in-the-cloud/2-compute-in-the-cloud.md
                  - Auto Scaling y Load Balancers: cloud/aws/aws-cloud-practitioner-essentials/2-compute-in-the-cloud/3-auto-scaling-and-load-balancers.md
              - 3. Explorando Servicios de Cómputo:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/3-exploring-compute-services/1-introduction.md
                  - Soluciones Serverless y Contenedores: cloud/aws/aws-cloud-practitioner-essentials/3-exploring-compute-services/2-serverless-containers-solutions.md
              - 4. Going Global:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/4-going-global/1-introduction.md
                  - Infraestructura Global de AWS: cloud/aws/aws-cloud-practitioner-essentials/4-going-global/2-aws-global-infrastructure.md
              - 5. Redes:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/5-networking/1-introduction.md
                  - Componentes de Red: cloud/aws/aws-cloud-practitioner-essentials/5-networking/2-network-components-in-the-aws-cloud.md
                  - Cloud en la Vida Real: cloud/aws/aws-cloud-practitioner-essentials/5-networking/3-cloud-in-real-life.md
              - 6. Almacenamiento:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/6-storage/1-introduction.md
                  - Almacenamiento en Bloques: cloud/aws/aws-cloud-practitioner-essentials/6-storage/2-block-storage.md
                  - Almacenamiento de Objetos: cloud/aws/aws-cloud-practitioner-essentials/6-storage/3-object-storage.md
                  - Almacenamiento de Archivos: cloud/aws/aws-cloud-practitioner-essentials/6-storage/4-file-storage.md
                  - Soluciones Adicionales: cloud/aws/aws-cloud-practitioner-essentials/6-storage/5-additional-storage-solutions.md
                  - Cloud en la Vida Real: cloud/aws/aws-cloud-practitioner-essentials/6-storage/6-cloud-in-real-life.md
              - 7. Bases de Datos:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/7-databases/1-introduction.md
                  - Servicios de Base de Datos AWS: cloud/aws/aws-cloud-practitioner-essentials/7-databases/2-aws-database-services.md
              - 8. IA, ML y Analítica de Datos:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/8-ai-ml-and-data-analytics/1-introduction.md
                  - IA y ML en AWS: cloud/aws/aws-cloud-practitioner-essentials/8-ai-ml-and-data-analytics/2-ai-ml-on-aws.md
                  - Analítica de Datos en AWS: cloud/aws/aws-cloud-practitioner-essentials/8-ai-ml-and-data-analytics/3-data-analytics-on-aws.md
                  - Cloud en la Vida Real: cloud/aws/aws-cloud-practitioner-essentials/8-ai-ml-and-data-analytics/4-cloud-in-real-life.md
              - 9. Seguridad:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/9-security/1-introduction.md
                  - Controles de Seguridad AWS: cloud/aws/aws-cloud-practitioner-essentials/9-security/2-aws-security-controls.md
              - 10. Monitoreo, Cumplimiento y Gobernanza:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/10-monitoring-compliance-and-governance-in-the-aws-cloud/1-introduction.md
                  - Servicios de Monitoreo y Cumplimiento: cloud/aws/aws-cloud-practitioner-essentials/10-monitoring-compliance-and-governance-in-the-aws-cloud/2-monitoring-and-compliance-services.md
              - 11. Precios y Soporte:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/11-pricing-and-support/1-introduction.md
                  - Conceptos de Precios: cloud/aws/aws-cloud-practitioner-essentials/11-pricing-and-support/2-aws-pricing.md
                  - Soporte en AWS: cloud/aws/aws-cloud-practitioner-essentials/11-pricing-and-support/3-aws-support.md
                  - Cloud en la Vida Real: cloud/aws/aws-cloud-practitioner-essentials/11-pricing-and-support/4-cloud-in-real-life.md
              - 12. Migración a la Nube:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/12-migrating-to-the-aws-cloud/1-introduction.md
                  - Frameworks y Estrategias: cloud/aws/aws-cloud-practitioner-essentials/12-migrating-to-the-aws-cloud/2-migration-frameworks-and-strategies.md
                  - Servicios y Herramientas: cloud/aws/aws-cloud-practitioner-essentials/12-migrating-to-the-aws-cloud/3-migration-services-and-tools.md
                  - Migración de Bases de Datos: cloud/aws/aws-cloud-practitioner-essentials/12-migrating-to-the-aws-cloud/4-migrating-databases-to-aws-cloud.md
                  - Migración de Datos: cloud/aws/aws-cloud-practitioner-essentials/12-migrating-to-the-aws-cloud/5-migrating-data-to-aws-cloud.md
              - 13. Soluciones Bien Arquitectadas:
                  - Introducción: cloud/aws/aws-cloud-practitioner-essentials/13-well-architected-solutions/1-introduction.md
                  - Servicios Especializados y Framework: cloud/aws/aws-cloud-practitioner-essentials/13-well-architected-solutions/2-aws-specialized-services-and-solutions.md
                  - Cloud en la Vida Real: cloud/aws/aws-cloud-practitioner-essentials/13-well-architected-solutions/3-cloud-in-real-life.md
  - Lenguajes:
      - Command Line:
          - Introducción: lenguages/commandline/1-introduction.md
          - Navegación: lenguages/commandline/2-navigation.md
          - Manipulación: lenguages/commandline/3-manipulation.md
          - Operadores: lenguages/commandline/4-operators.md
          - Ejemplos: lenguages/commandline/5-examples.md
          - Resumen Visual: lenguages/commandline/6-visual-summary.md
          - Documentación: lenguages/commandline/doc.md
      - CSS:
          - Introducción: lenguages/css/1-introduction.md
          - Sintaxis y Selectores: lenguages/css/2-syntax-and-selectors.md
          - Propiedades y Valores: lenguages/css/3-properties-and-values.md
          - Modelo de Caja: lenguages/css/4-box-model.md
          - Layout: lenguages/css/5-layout.md
          - Tipografía: lenguages/css/6-typography.md
          - Colores y Fondos: lenguages/css/7-colors-and-backgrounds.md
          - Bordes y Sombras: lenguages/css/8-borders-and-shadows.md
          - Transiciones y Animaciones: lenguages/css/9-transitions-and-animations.md
          - Media Queries y Responsive: lenguages/css/10-media-queries-and-responsive.md
          - Pseudo-clases y Elementos: lenguages/css/11-pseudo-classes-and-elements.md
          - Buenas Prácticas: lenguages/css/12-best-practices.md
          - Herramientas y Workflows: lenguages/css/13-tools-and-workflows.md
          - Ejemplos: lenguages/css/14-examples.md
          - Resumen Visual: lenguages/css/15-visual-summary.md
      - Git:
          - Git: lenguages/git/git.md
          - GitHub: lenguages/git/github.md
      - JavaScript:
          - Introducción: lenguages/javascript/1-introduction.md
          - Variables y Tipos: lenguages/javascript/2-variables-and-types.md
          - Operadores: lenguages/javascript/3-operators.md
          - Estructuras de Control: lenguages/javascript/4-control-structures.md
          - Funciones: lenguages/javascript/5-functions.md
          - Objetos y Arreglos: lenguages/javascript/6-objects-and-arrays.md
          - DOM Básico: lenguages/javascript/7-dom-basics.md
          - JSON y Fetch: lenguages/javascript/8-json-and-fetch.md
          - Manejo de Errores: lenguages/javascript/9-error-handling.md
          - Buenas Prácticas: lenguages/javascript/10-best-practices.md
          - Estructuras de Datos Avanzadas: lenguages/javascript/11-advanced-data-structures.md
          - Módulos y Namespaces: lenguages/javascript/12-modules-and-namespaces.md
          - Clases y OOP: lenguages/javascript/13-classes-and-oop.md
          - Patrones y Prácticas: lenguages/javascript/14-patterns-and-practices.md
          - Herramientas y Workflow: lenguages/javascript/15-tools-and-workflow.md
          - Ejemplos y Recetas: lenguages/javascript/16-examples-and-recipes.md
          - Resumen Visual: lenguages/javascript/17-visual-summary.md
      - Python:
          - Introducción: lenguages/python/1-introduction.md
          - Fundamentos: lenguages/python/2-basics.md
          - Estructuras de Control: lenguages/python/3-control-structures.md
          - Estructuras de Datos: lenguages/python/4-data-structures.md
          - Funciones: lenguages/python/5-functions.md
          - Manejo de Errores: lenguages/python/6-error-handling.md
          - Entradas y Salidas: lenguages/python/7-input-output.md
          - Módulos y Paquetes: lenguages/python/8-modules-and-packages.md
          - Programación Orientada a Objetos: lenguages/python/9-oop.md
          - Estructuras de Datos Avanzadas: lenguages/python/10-advanced-data-structures.md
          - Iteradores y Generadores: lenguages/python/11-iterators-generators.md
          - Decoradores y Context Managers: lenguages/python/12-decorators-context-managers.md
          - Virtualenv y pip: lenguages/python/13-virtualenv-pip.md
          - Testing: lenguages/python/14-testing.md
          - Comprehensions y Lambda: lenguages/python/15-comprehensions-lambda.md
          - Expresiones Regulares: lenguages/python/16-regular-expressions.md
          - Fecha y Hora: lenguages/python/17-datetime.md
          - Networking: lenguages/python/18-networking.md
          - Concurrencia: lenguages/python/19-concurrency.md
          - GUI: lenguages/python/20-gui.md
          - Web Frameworks: lenguages/python/21-web-frameworks.md
          - Data Science: lenguages/python/22-data-science.md
          - Buenas Prácticas: lenguages/python/23-best-practices.md
      - SQL:
          - Básico:
              - Introducción: lenguages/sql/basic/1-introduction.md
              - Estructura de Tablas: lenguages/sql/basic/2-tables-structure.md
              - Consultas Básicas: lenguages/sql/basic/3-basic-querys.md
              - Agregación y Clustering: lenguages/sql/basic/4-aggregation-clustering.md
              - Joins: lenguages/sql/basic/5-joins.md
              - Subconsultas: lenguages/sql/basic/6-subquerys.md
          - Intermedio:
              - Manipulación de Datos: lenguages/sql/intermediate/7-data-manipulation.md
              - Gestión de Estructura: lenguages/sql/intermediate/8-management-structure.md
              - Transacciones: lenguages/sql/intermediate/9-transactions.md
          - Avanzado:
              - Funciones y Expresiones: lenguages/sql/advanced/10-functions-expressions.md
              - Procedimientos y Funciones: lenguages/sql/advanced/11-procedures-functions.md
              - Triggers: lenguages/sql/advanced/12-triggers.md
              - Seguridad y Usuarios: lenguages/sql/advanced/13-security-users.md
              - Optimización: lenguages/sql/advanced/14-optimization.md
              - Avanzado: lenguages/sql/advanced/15-advanced.md
              - Buenas Prácticas: lenguages/sql/advanced/16-good-practices.md
  - Herramientas:
      - Comandos Comunes: herramientas/general-cheatsheet.md
      - NMAP: herramientas/nmap.md
      - Metasploit: herramientas/metasploit.md
      - Metasploitable VM: herramientas/metasploitableVM.md
      - Armitage: herramientas/armitage.md
      - WPScan: herramientas/wpscan.md
  - Pentesting:
      - Introduccion: pentest/introduccion.md
      - Pentest en APIs: pentest/pentest-apis.md
  - Laboratorio:
      - NMAP: laboratorio/nmap-lab.md
      - EtterCap: laboratorio/ettercap-lab.md
      - WireShark: laboratorio/wireshark-lab.md
      - Metasploit: laboratorio/metasploit-lab.md
      - Metasploitable VM: laboratorio/metasploitableVM.md
      - Nikto (UNDER CONSTRUCTION): laboratorio/nikto.md
      - Burpsuite: laboratorio/burpsuite-lab.md
      - Transferencia de Archivos: laboratorio/transferencia-archivos.md
      - Ataque a Redes Inalambricas: laboratorio/ataques-redes-inalambricas-lab.md
      - Como Vulnerar un Sitio Web: laboratorio/vulnerar-sitioweb.md
      - WPScan: laboratorio/wpscan-lab.md
  - Configuracion de Maquina:
      - Particiones: configuracion-maquina/particiones.md
      - Terminal: configuracion-maquina/terminal.md
      - GUI: configuracion-maquina/gui.md
      - Extras: configuracion-maquina/extras.md
      - Herramientas: configuracion-maquina/herramientas.md

site_url: https://emm4nuelcm.github.io/my-knowledge-base/
extra_css:
  - assets/extra.css
